import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const makeIcon=(type)=>(props)=><svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={type==='check'?'M5 12l4 4L19 6':type==='plus'?'M12 5v14M5 12h14':type==='x'?'M6 6l12 12M18 6L6 18':type==='arrow'?'M5 12h14m-5-5 5 5-5 5':type==='flame'?'M12 22c4 0 7-3 7-7 0-3-2-6-5-9 0 3-2 4-3 5 0-4-2-7-2-9-3 4-5 8-4 13 0 4 3 7 7 7z':type==='heart'?'M20 5c-2-2-5-2-7 1l-1 1-1-1C9 3 6 3 4 5c-3 3-1 7 1 9l7 7 7-7c2-2 4-6 1-9z':type==='wind'?'M3 8h11c3 0 3-4 0-4M3 12h16c3 0 3 4 0 4M3 16h8':type==='chat'?'M4 5h16v12H9l-5 4V5z':type==='home'?'M3 11l9-8 9 8v10h-6v-7H9v7H3z':type==='trophy'?'M8 4h8v5c0 4-2 6-4 6s-4-2-4-6V4zm0 2H4c0 4 2 6 5 6m7-6h4c0 4-2 6-5 6m-3 3v5m-4 0h8':type==='leaf'?'M20 4C10 4 4 9 4 16c4 1 8 0 11-3M4 20c3-6 7-9 13-12':type==='send'?'M3 4l18 8-18 8 4-8-4-8zm4 8h14':type==='user'?'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 8zm-8 9c1-5 4-7 8-7s7 2 8 7':type==='moon'?'M20 15A8 8 0 0 1 9 4a8 8 0 1 0 11 11z':type==='pin'?'M12 22s7-7 7-13A7 7 0 0 0 5 9c0 6 7 13 7 13zm0-10a3 3 0 1 0 0-6 3 3 0 0 0 6z':type==='coffee'?'M4 8h13v7a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5V8zm13 2h2a3 3 0 0 1 0 6h-2M7 4v2m4-2v2':type==='bell'?'M6 17h12l-2-3V9a4 4 0 0 0-8 0v5l-2 3zm4 3h4':type==='shield'?'M12 3l8 3v6c0 5-3 8-8 10-5-2-8-5-8-10V6l8-3zM9 12l2 2 4-5':type==='spark'?'M12 2l2 7 7 3-7 2-2 8-2-8-7-2 7-3 2-7z':'M4 18V8m5 10V4m5 14v-7m5 7V6'}/></svg>;
const Home=makeIcon('home'),Activity=makeIcon('chart'),Trophy=makeIcon('trophy'),MessageCircle=makeIcon('chat'),Flame=makeIcon('flame'),Wind=makeIcon('wind'),Plus=makeIcon('plus'),ArrowRight=makeIcon('arrow'),X=makeIcon('x'),Check=makeIcon('check'),ChevronRight=makeIcon('arrow'),MapPin=makeIcon('pin'),Users=makeIcon('user'),Coffee=makeIcon('coffee'),BriefcaseBusiness=makeIcon('chart'),Moon=makeIcon('moon'),Send=makeIcon('send'),Sparkles=makeIcon('spark'),Heart=makeIcon('heart'),ShieldCheck=makeIcon('shield'),Bell=makeIcon('bell'),Leaf=makeIcon('leaf');

const screens=['today','track','progress','achievements','chat'];
const nav=[['today',Home,'Today'],['track',Activity,'Track'],['progress',Leaf,'Progress'],['achievements',Trophy,'Rewards'],['chat',MessageCircle,'Support']];

function Ring({value=68,size=128,label='7 days'}){
 const r=52,c=2*Math.PI*r;
 return <div className="ring" style={{width:size,height:size}}><svg viewBox="0 0 120 120"><circle className="ring-bg" cx="60" cy="60" r={r}/><circle className="ring-fill" cx="60" cy="60" r={r} strokeDasharray={c} strokeDashoffset={c*(1-value/100)}/></svg><div><b>{label}</b><span>smoke-free</span></div></div>
}
function Logo(){return <div className="logo"><span><Wind/></span><b>Clearway</b></div>}

function Onboarding({finish}){
 const [step,setStep]=useState(0); const [choice,setChoice]=useState('Health');
 const data=[
  {eyebrow:'A calmer way forward',title:'Every craving passes.',copy:'Clearway turns difficult minutes into small, steady wins—without judgment or pressure.'},
  {eyebrow:'Make it yours',title:'What matters most?',copy:'Your reason will be here when motivation feels far away.'},
  {eyebrow:'Your first milestone',title:'Start with seven days.',copy:'A focused plan, daily support, and tools that meet you in the moment.'}
 ];
 return <main className="onboard"><div className="onboard-top"><Logo/><span>Step {step+1} of 3</span></div><section className="onboard-grid">
  <div className="onboard-copy"><span className="eyebrow">{data[step].eyebrow}</span><h1>{data[step].title}</h1><p>{data[step].copy}</p>
  {step===1&&<div className="reason-grid">{[['Health',Heart],['Family',Users],['Freedom',Wind],['Confidence',Sparkles]].map(([t,I])=><button className={choice===t?'selected':''} onClick={()=>setChoice(t)} key={t}><I/><span>{t}</span>{choice===t&&<Check/>}</button>)}</div>}
  {step===2&&<div className="starter"><Ring value={14} label="Day 1"/><div><b>Your quit date</b><span>Today · A fresh start</span><hr/><b>Daily check-in</b><span>8:00 AM · About 30 seconds</span></div></div>}
  <button className="primary" onClick={()=>step<2?setStep(step+1):finish()}>{step<2?'Continue':'Begin my journey'}<ArrowRight/></button>
  <button className="text-btn" onClick={finish}>I already have a quit date</button></div>
  <div className={'visual visual-'+step}><div className="orb"><div className="path"></div><div className="milestone"><Sparkles/><b>{step===0?'One moment at a time':step===1?choice+' is your why':'Your plan is ready'}</b><span>{step===0?'You’re stronger than the urge.':step===1?'We’ll keep it close.':'Small steps. Real momentum.'}</span></div></div></div>
 </section><div className="dots">{data.map((_,i)=><i className={i===step?'active':''} key={i}/>)}</div></main>
}

function Today({go,setModal}){return <div className="screen today"><header><div><span className="eyebrow">SATURDAY · DAY 7</span><h1>Good morning, Maya.</h1><p>You’ve protected 168 hours. Let’s keep today light.</p></div><button className="avatar">MK</button></header>
 <section className="hero-progress"><Ring/><div className="hero-copy"><div className="streak"><Flame/>7 day streak <span>+20 XP today</span></div><h2>Your body is already healing.</h2><p>Carbon monoxide levels are back to normal. Your lungs are clearing more easily.</p><button onClick={()=>go('progress')}>See your recovery <ArrowRight/></button></div><div className="xp"><span>LEVEL 4</span><b>340 <small>XP</small></b><i><em/></i><small>160 XP to level 5</small></div></section>
 <div className="section-title"><div><span className="eyebrow">RIGHT NOW</span><h2>How are you feeling?</h2></div><span>Tap to check in</span></div>
 <div className="moods">{[['Calm','😌'],['Okay','🙂'],['Restless','🫨'],['Craving','🌊']].map(([x,e])=><button onClick={()=>x==='Craving'&&setModal('craving')} key={x}><span>{e}</span>{x}</button>)}</div>
 <div className="today-bottom"><div><span className="eyebrow">TODAY’S FOCUS</span><h2>After-coffee cravings</h2><p>Your usual trigger peaks around 10:30 AM. A 2-minute reset is ready when you need it.</p><button className="outline" onClick={()=>setModal('intervention')}><Wind/>Try the breathing reset</button></div><blockquote>“An urge is a wave. You don’t have to fight it—just let it pass beneath you.”<span>Dr. Lena Ortiz · Behavioral psychologist</span></blockquote></div>
 </div>}

function Track({setModal}){const [level,setLevel]=useState(6);return <div className="screen"><header><div><span className="eyebrow">QUICK CHECK-IN</span><h1>Log a craving</h1><p>Notice it, name it, and let it pass. This takes about 20 seconds.</p></div><button className="close"><X/></button></header><div className="tracker-layout"><section className="intensity"><span className="eyebrow">INTENSITY</span><div className="level"><b>{level}</b><span>/ 10 · {level>7?'Strong':level>4?'Noticeable':'Mild'}</span></div><input type="range" min="1" max="10" value={level} onChange={e=>setLevel(e.target.value)}/><div className="scale"><span>Just a thought</span><span>Hard to ignore</span></div></section><section className="trigger"><span className="eyebrow">WHAT TRIGGERED IT?</span><h2>Add context</h2><div className="trigger-grid">{[[Coffee,'Coffee'],[BriefcaseBusiness,'Stress'],[Users,'Social'],[Moon,'Routine'],[MapPin,'Place'],[Plus,'Other']].map(([I,t],i)=><button className={i===0?'selected':''} key={t}><I/><span>{t}</span></button>)}</div><label>Optional note<textarea placeholder="What was happening?">Finished breakfast and made coffee.</textarea></label><button className="primary" onClick={()=>setModal('intervention')}><Check/>Save & get support</button></section></div></div>}

function Progress(){return <div className="screen"><header><div><span className="eyebrow">YOUR RECOVERY</span><h1>Progress you can feel.</h1><p>Seven days of choosing yourself, measured in more than time.</p></div><select><option>Last 7 days</option></select></header><section className="metric-line"><Ring value={68}/><div><span>TIME SMOKE-FREE</span><b>7 days, 4 hours</b><small>Longest streak · keep going</small></div><div><span>MONEY SAVED</span><b>$84.50</b><small>About 6 lunches</small></div><div><span>CIGARETTES AVOIDED</span><b>121</b><small>Every one counts</small></div></section><section className="chart-section"><div className="section-title"><div><span className="eyebrow">CRAVING PATTERN</span><h2>Urges are getting quieter</h2></div><span>−38% average intensity</span></div><div className="chart"><div className="bars">{[78,62,72,50,44,38,30].map((h,i)=><div key={i}><i style={{height:h+'%'}}/><span>{['S','M','T','W','T','F','S'][i]}</span></div>)}</div></div></section><section className="recovery"><div><span className="eyebrow">BODY RECOVERY</span><h2>What’s changing now</h2></div>{[['Oxygen levels','Back to normal','100%'],['Taste & smell','Sharpening','72%'],['Lung function','Improving','38%']].map(([a,b,c])=><div className="recovery-row" key={a}><span><b>{a}</b><small>{b}</small></span><i><em style={{width:c}}/></i><b>{c}</b></div>)}</section></div>}

function Achievements(){let badges=[['First Step','Logged your first craving',Check,'earned'],['Week One','7 days smoke-free',Flame,'earned'],['Wave Rider','Surfed 10 cravings',Wind,'earned'],['Clear Mind','Complete 5 breathing resets',Sparkles,''],['Two Weeks','14 days smoke-free',Trophy,''],['Helping Hand','Message your partner 7 times',Users,'']];return <div className="screen"><header><div><span className="eyebrow">MOMENTUM</span><h1>Your wins, collected.</h1><p>Each badge marks something hard that you made possible.</p></div><div className="level-chip"><b>Level 4</b><span>340 / 500 XP</span></div></header><section className="featured-badge"><div className="badge-big"><Flame/></div><div><span className="eyebrow">NEW THIS WEEK</span><h2>Week One</h2><p>Seven full days of choosing your future. That’s 168 hours of proof.</p><span className="xp-gain">+100 XP</span></div></section><div className="badge-grid">{badges.map(([a,b,I,s])=><div className={s} key={a}><span><I/></span><div><b>{a}</b><small>{b}</small></div>{s&&<Check/>}</div>)}</div></div>}

function Chat(){const [sent,setSent]=useState(false);return <div className="screen chat"><header><div><span className="eyebrow">ACCOUNTABILITY PARTNER</span><h1>Jamie Chen</h1><p><i/> Online · Here for your check-ins</p></div><button className="icon-btn"><Bell/></button></header><div className="chat-window"><div className="chat-date">TODAY</div><div className="message them"><span className="mini-avatar">JC</span><div>One week today!! How are you feeling?<small>9:14 AM</small></div></div><div className="message me"><div>Honestly proud. Coffee was tough, but I used the breathing reset instead.<small>9:18 AM · Read</small></div></div><div className="message them"><span className="mini-avatar">JC</span><div>That’s huge. You didn’t just avoid it—you practiced a new response 💚<small>9:19 AM</small></div></div>{sent&&<div className="message me"><div>Thanks for being in my corner. It really helps.<small>Just now</small></div></div>}<div className="quick-replies"><span>QUICK REPLY</span>{['I made it through','Could use support','Feeling strong today'].map(x=><button onClick={()=>setSent(true)} key={x}>{x}</button>)}</div></div><div className="composer"><button><Plus/></button><input placeholder="Message Jamie…"/><button className="send" onClick={()=>setSent(true)}><Send/></button></div></div>}

function Intervention({close}){const [done,setDone]=useState(false);return <div className="overlay"><div className="intervention"><button className="close" onClick={close}><X/></button>{!done?<><div className="breath-orb"><Wind/></div><span className="eyebrow">2-MINUTE RESET</span><h1>Let the urge move through.</h1><p>Follow the circle. Breathe in slowly, then let go.</p><div className="breathing"><span>BREATHE IN</span><b>4</b></div><button className="primary" onClick={()=>setDone(true)}>I’m feeling better</button><button className="text-btn">Try another technique</button></>:<><div className="success"><Check/></div><span className="eyebrow">YOU DID IT</span><h1>That craving passed.</h1><p>You gave yourself space instead of reacting. That’s how the pathway changes.</p><div className="reward">+15 XP <span>Resilience grows through repetition</span></div><button className="primary" onClick={close}>Back to my day</button></>}</div></div>}

function App(){const [onboard,setOnboard]=useState(true),[screen,setScreen]=useState('today'),[modal,setModal]=useState(null); if(onboard)return <Onboarding finish={()=>setOnboard(false)}/>;let Page={today:Today,track:Track,progress:Progress,achievements:Achievements,chat:Chat}[screen];return <div className="app"><aside><Logo/><nav>{nav.map(([s,I,t])=><button className={screen===s?'active':''} onClick={()=>setScreen(s)} key={s}><I/><span>{t}</span>{s==='chat'&&<i/>}</button>)}</nav><div className="nav-support"><ShieldCheck/><b>Your plan</b><span>Day 7 of 30</span><i><em/></i></div><button className="profile"><span>MK</span><div><b>Maya Kim</b><small>Level 4 · 340 XP</small></div><ChevronRight/></button></aside><main><Page go={setScreen} setModal={setModal}/></main><button className="mobile-log" onClick={()=>setScreen('track')}><Plus/></button>{modal&&<Intervention close={()=>setModal(null)}/>}</div>}

createRoot(document.getElementById('root')).render(<App/>);
